# Percobaan Data Transformation

Notebook ini dibuat sesuai bagian **C. Percobaan** pada modul:
- Membuat DataFrame df
- Handling Missing Values: Imputation dan Deletion
- Encoding: Label Encoding dan One-Hot Encoding
- Scaling: Normalization dan Standardization
- Creating New Feature

## 1. Import Library

In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

## 2. Membuat Dataset ke dalam DataFrame `df`

In [2]:
data = {
    "Jam_Belajar": [23, 19, 24, 29, 19, 19, 29, 25, 17, 23,
                    17, 17, 21, 9, 10, 17, 14, 22, 15, 12,
                    29, 19, 20, 11, 17, 21, 13, 22, 16, 18],

    "Kehadiran": [84, 64, 98, 89, 92, 88, 84, 78, 94, 98,
                  80, 97, 83, 82, 78, 68, 60, 70, 80, 75,
                  78, 99, 74, 78, 65, 62, 91, 83, 90, 66],

    "Ekstrakulikuler": ["Tidak", "Tidak", "Iya", "Iya", "Iya", "Iya", "Iya", "Iya", "Tidak", "Iya",
                        "Tidak", "Iya", "Iya", "Iya", "Iya", "Tidak", "Iya", "Iya", "Iya", "Iya",
                        "Tidak", "Tidak", "Tidak", "Iya", "Iya", "Iya", "Tidak", "Iya", "Tidak", "Tidak"],

    "Jam_Tidur": [7, 8, np.nan, 8, 6, 8, 7, np.nan, 6, np.nan,
                  8, 6, 8, 8, 8, 8, 10, np.nan, 9, np.nan,
                  5, 6, np.nan, 8, 5, 6, 6, 6, 4, 4],

    "Sesi_Les": [0, 2, 2, 1, 3, 3, 1, 1, 0, 0,
                 4, 2, 2, 2, 1, 2, 0, 1, 3, 3,
                 0, 1, 1, 1, 2, 0, 1, 0, 1, 2],

    "Jarak_Dari_Rumah": ["Dekat", "Sedang", "Dekat", "Sedang", "Dekat", "Dekat", "Sedang", "Jauh", "Dekat", "Sedang",
                         "Sedang", "Dekat", "Dekat", "Dekat", "Dekat", "Dekat", "Dekat", "Dekat", "Sedang", "Dekat",
                         "Sedang", "Dekat", "Sedang", "Sedang", "Dekat", "Jauh", "Sedang", "Sedang", "Sedang", "Dekat"],

    "Jenis_kelamin": ["Laki-laki", "Perempuan", "Laki-laki", "Laki-laki", "Perempuan", "Laki-laki", "Laki-laki", "Laki-laki", "Laki-laki", "Laki-laki",
                      "Laki-laki", "Laki-laki", "Laki-laki", "Laki-laki", "Laki-laki", "Perempuan", "Laki-laki", "Perempuan", "Perempuan", "Laki-laki",
                      "Perempuan", "Laki-laki", "Perempuan", "Laki-laki", "Perempuan", "Laki-laki", "Perempuan", "Laki-laki", "Perempuan", "Laki-laki"],

    "Nilai_Ujian": [67, 61, 74, 71, 70, 71, 67, 66, 69, 72,
                    68, 71, 70, 66, 65, 64, 60, 65, 67, 66,
                    69, 72, 66, 66, 63, 64, 65, 71, 66, 64]
}

df = pd.DataFrame(data)

df

,Jam_Belajar,Kehadiran,Ekstrakulikuler,Jam_Tidur,Sesi_Les,Jarak_Dari_Rumah,Jenis_kelamin,Nilai_Ujian
0,23,84,Tidak,7.0,0,Dekat,Laki-laki,67
1,19,64,Tidak,8.0,2,Sedang,Perempuan,61
2,24,98,Iya,NaN,2,Dekat,Laki-laki,74
3,29,89,Iya,8.0,1,Sedang,Laki-laki,71
4,19,92,Iya,6.0,3,Dekat,Perempuan,70
5,19,88,Iya,8.0,3,Dekat,Laki-laki,71
6,29,84,Iya,7.0,1,Sedang,Laki-laki,67
7,25,78,Iya,NaN,1,Jauh,Laki-laki,66
8,17,94,Tidak,6.0,0,Dekat,Laki-laki,69
9,23,98,Iya,NaN,0,Sedang,Laki-laki,72
10,17,80,Tidak,8.0,4,Sedang,Laki-laki,68
11,17,97,Iya,6.0,2,Dekat,Laki-laki,71
12,21,83,Iya,8.0,2,Dekat,Laki-laki,70
13,9,82,Iya,8.0,2,Dekat,Laki-laki,66
14,10,78,Iya,8.0,1,Dekat,Laki-laki,65
15,17,68,Tidak,8.0,2,Dekat,Perempuan,64
16,14,60,Iya,10.0,0,Dekat,Laki-laki,60
17,22,70,Iya,NaN,1,Dekat,Perempuan,65
18,15,80,Iya,9.0,3,Sedang,Perempuan,67
19,12,75,Iya,NaN,3,Dekat,Laki-laki,66
20,29,78,Tidak,5.0,0,Sedang,Perempuan,69
21,19,99,Tidak,6.0,1,Dekat,Laki-laki,72
22,20,74,Tidak,NaN,1,Sedang,Perempuan,66
23,11,78,Iya,8.0,1,Sedang,Laki-laki,66
24,17,65,Iya,5.0,2,Dekat,Perempuan,63
25,21,62,Iya,6.0,0,Jauh,Laki-laki,64
26,13,91,Tidak,6.0,1,Sedang,Perempuan,65
27,22,83,Iya,6.0,0,Sedang,Laki-laki,71
28,16,90,Tidak,4.0,1,Sedang,Perempuan,66
29,18,66,Tidak,4.0,2,Dekat,Laki-laki,64

## 3. Cek Informasi Dataset

In [3]:
print("Jumlah baris dan kolom:", df.shape)
print("\nInformasi dataset:")
df.info()

Jumlah baris dan kolom: (30, 8)

Informasi dataset:
<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Jam_Belajar       30 non-null     int64
 1   Kehadiran         30 non-null     int64
 2   Ekstrakulikuler   30 non-null     str
 3   Jam_Tidur         24 non-null     float64
 4   Sesi_Les          30 non-null     int64
 5   Jarak_Dari_Rumah  30 non-null     str
 6   Jenis_kelamin     30 non-null     str
 7   Nilai_Ujian       30 non-null     int64
dtypes: float64(1), int64(4), str(3)
memory usage: 2.0 KB

In [4]:
print("Missing value sebelum ditangani:")
print(df.isnull().sum())

Missing value sebelum ditangani:
Jam_Belajar         0
Kehadiran           0
Ekstrakulikuler     0
Jam_Tidur           6
Sesi_Les            0
Jarak_Dari_Rumah    0
Jenis_kelamin       0
Nilai_Ujian         0
dtype: int64

## 4.1 Handling Missing Values 
### A. Imputation

Pada bagian ini, nilai kosong pada kolom Jam_Tidur diisi menggunakan nilai rata-rata atau mean().

In [5]:
df_imputation = df.copy()

rata_rata_jam_tidur = df_imputation['Jam_Tidur'].mean()
print("Rata-rata Jam_Tidur:", rata_rata_jam_tidur)

df_imputation['Jam_Tidur'] = df_imputation['Jam_Tidur'].fillna(rata_rata_jam_tidur)

print("\nMissing value setelah imputation:")
print(df_imputation.isnull().sum())

df_imputation.head(10)

Rata-rata Jam_Tidur: 6.875

Missing value setelah imputation:
Jam_Belajar         0
Kehadiran           0
Ekstrakulikuler     0
Jam_Tidur           0
Sesi_Les            0
Jarak_Dari_Rumah    0
Jenis_kelamin       0
Nilai_Ujian         0
dtype: int64

,Jam_Belajar,Kehadiran,Ekstrakulikuler,Jam_Tidur,Sesi_Les,Jarak_Dari_Rumah,Jenis_kelamin,Nilai_Ujian
0,23,84,Tidak,7.000,0,Dekat,Laki-laki,67
1,19,64,Tidak,8.000,2,Sedang,Perempuan,61
2,24,98,Iya,6.875,2,Dekat,Laki-laki,74
3,29,89,Iya,8.000,1,Sedang,Laki-laki,71
4,19,92,Iya,6.000,3,Dekat,Perempuan,70
5,19,88,Iya,8.000,3,Dekat,Laki-laki,71
6,29,84,Iya,7.000,1,Sedang,Laki-laki,67
7,25,78,Iya,6.875,1,Jauh,Laki-laki,66
8,17,94,Tidak,6.000,0,Dekat,Laki-laki,69
9,23,98,Iya,6.875,0,Sedang,Laki-laki,72

## 4.1 Handling Missing Values
### B. Deletion

Pada bagian ini, baris yang memiliki nilai kosong pada kolom Jam_Tidur dihapus menggunakan dropna().

In [6]:
df_deletion = df.copy()

print("Jumlah data sebelum dropna:", len(df_deletion))

df_deletion.dropna(subset=['Jam_Tidur'], how='any', inplace=True)

print("Jumlah data setelah dropna:", len(df_deletion))
print("\nMissing value setelah deletion/dropna:")
print(df_deletion.isnull().sum())

df_deletion.head(10)

Jumlah data sebelum dropna: 30
Jumlah data setelah dropna: 24

Missing value setelah deletion/dropna:
Jam_Belajar         0
Kehadiran           0
Ekstrakulikuler     0
Jam_Tidur           0
Sesi_Les            0
Jarak_Dari_Rumah    0
Jenis_kelamin       0
Nilai_Ujian         0
dtype: int64

,Jam_Belajar,Kehadiran,Ekstrakulikuler,Jam_Tidur,Sesi_Les,Jarak_Dari_Rumah,Jenis_kelamin,Nilai_Ujian
0,23,84,Tidak,7.0,0,Dekat,Laki-laki,67
1,19,64,Tidak,8.0,2,Sedang,Perempuan,61
3,29,89,Iya,8.0,1,Sedang,Laki-laki,71
4,19,92,Iya,6.0,3,Dekat,Perempuan,70
5,19,88,Iya,8.0,3,Dekat,Laki-laki,71
6,29,84,Iya,7.0,1,Sedang,Laki-laki,67
8,17,94,Tidak,6.0,0,Dekat,Laki-laki,69
10,17,80,Tidak,8.0,4,Sedang,Laki-laki,68
11,17,97,Iya,6.0,2,Dekat,Laki-laki,71
12,21,83,Iya,8.0,2,Dekat,Laki-laki,70

## Catatan

Untuk tahap berikutnya digunakan df_imputation, karena data tetap lengkap 30 baris dan missing value sudah diisi dengan rata-rata.

In [7]:
df_encoded = df_imputation.copy()
df_encoded.head()

,Jam_Belajar,Kehadiran,Ekstrakulikuler,Jam_Tidur,Sesi_Les,Jarak_Dari_Rumah,Jenis_kelamin,Nilai_Ujian
0,23,84,Tidak,7.000,0,Dekat,Laki-laki,67
1,19,64,Tidak,8.000,2,Sedang,Perempuan,61
2,24,98,Iya,6.875,2,Dekat,Laki-laki,74
3,29,89,Iya,8.000,1,Sedang,Laki-laki,71
4,19,92,Iya,6.000,3,Dekat,Perempuan,70

## 4.2 Encoding
### A. Label Encoding untuk Ekstrakulikuler

Fitur Ekstrakulikuler diubah secara manual:
- Iya menjadi 1
- Tidak menjadi 0

In [8]:
df_encoded['Ekstrakulikuler'] = df_encoded['Ekstrakulikuler'].apply(
    lambda x: 1 if x == 'Iya' else (0 if x == 'Tidak' else None)
)

df_encoded[['Ekstrakulikuler']].head(10)

   Ekstrakulikuler
0                0
1                0
2                1
3                1
4                1
5                1
6                1
7                1
8                0
9                1

## 4.2 Encoding 
A. Label Encoding untuk Jenis_kelamin

Fitur Jenis_kelamin diubah menggunakan LabelEncoder dari library sklearn.

In [9]:
le = LabelEncoder()

df_encoded['Jenis_kelamin'] = le.fit_transform(df_encoded['Jenis_kelamin'])

print("Kelas pada LabelEncoder:", le.classes_)
df_encoded[['Jenis_kelamin']].head(10)

Kelas pada LabelEncoder: ['Laki-laki' 'Perempuan']

   Jenis_kelamin
0              0
1              1
2              0
3              0
4              1
5              0
6              0
7              0
8              0
9              0

## 4.2 Encoding 
B. One-Hot Encoding untuk Jarak_Dari_Rumah

Fitur Jarak_Dari_Rumah diubah menjadi beberapa kolom biner menggunakan pd.get_dummies().

In [10]:
df_encoded = pd.get_dummies(
    df_encoded,
    prefix=['Jarak_Rumah'],
    columns=['Jarak_Dari_Rumah'],
    dtype=int
)

df_encoded.head(10)

,Jam_Belajar,Kehadiran,Ekstrakulikuler,Jam_Tidur,Sesi_Les,Jenis_kelamin,Nilai_Ujian,Jarak_Rumah_Dekat,Jarak_Rumah_Jauh,Jarak_Rumah_Sedang
0,23,84,0,7.000,0,0,67,1,0,0
1,19,64,0,8.000,2,1,61,0,0,1
2,24,98,1,6.875,2,0,74,1,0,0
3,29,89,1,8.000,1,0,71,0,0,1
4,19,92,1,6.000,3,1,70,1,0,0
5,19,88,1,8.000,3,0,71,1,0,0
6,29,84,1,7.000,1,0,67,0,0,1
7,25,78,1,6.875,1,0,66,0,1,0
8,17,94,0,6.000,0,0,69,1,0,0
9,23,98,1,6.875,0,0,72,0,0,1

## 4.3 Scaling 
### A. Normalization

Normalization menggunakan MinMaxScaler, sehingga nilai fitur berada pada rentang 0 sampai 1.

In [11]:
scaler = MinMaxScaler()

df_normalized = pd.DataFrame(
    scaler.fit_transform(df_encoded),
    columns=df_encoded.columns
)

df_normalized.head(10)

,Jam_Belajar,Kehadiran,Ekstrakulikuler,Jam_Tidur,Sesi_Les,Jenis_kelamin,Nilai_Ujian,Jarak_Rumah_Dekat,Jarak_Rumah_Jauh,Jarak_Rumah_Sedang
0,0.70,0.615385,0.0,0.500000,0.00,0.0,0.500000,1.0,0.0,0.0
1,0.50,0.102564,0.0,0.666667,0.50,1.0,0.071429,0.0,0.0,1.0
2,0.75,0.974359,1.0,0.479167,0.50,0.0,1.000000,1.0,0.0,0.0
3,1.00,0.743590,1.0,0.666667,0.25,0.0,0.785714,0.0,0.0,1.0
4,0.50,0.820513,1.0,0.333333,0.75,1.0,0.714286,1.0,0.0,0.0
5,0.50,0.717949,1.0,0.666667,0.75,0.0,0.785714,1.0,0.0,0.0
6,1.00,0.615385,1.0,0.500000,0.25,0.0,0.500000,0.0,0.0,1.0
7,0.80,0.461538,1.0,0.479167,0.25,0.0,0.428571,0.0,1.0,0.0
8,0.40,0.871795,0.0,0.333333,0.00,0.0,0.642857,1.0,0.0,0.0
9,0.70,0.974359,1.0,0.479167,0.00,0.0,0.857143,0.0,0.0,1.0

## 4.3 Scaling 
### B. Standardization

Standardization menggunakan StandardScaler, sehingga data memiliki rata-rata mendekati 0 dan standar deviasi mendekati 1. Data yang digunakan adalah data hasil encoding, bukan data hasil normalisasi.

In [12]:
scaler = StandardScaler()

scaled_data = scaler.fit_transform(df_encoded)

df_standardized = pd.DataFrame(
    scaled_data,
    columns=df_encoded.columns
)

df_standardized.head(10)

,Jam_Belajar,Kehadiran,Ekstrakulikuler,Jam_Tidur,Sesi_Les,Jenis_kelamin,Nilai_Ujian,Jarak_Rumah_Dekat,Jarak_Rumah_Jauh,Jarak_Rumah_Sedang
0,0.783885,0.274150,-1.314257,0.092635,-1.292461,-0.707107,-0.059868,0.935414,-0.267261,-0.816497
1,0.019119,-1.513783,-1.314257,0.833715,0.553912,1.414214,-1.855921,-1.069045,-0.267261,1.224745
2,0.975076,1.525703,0.760886,0.000000,0.553912,-0.707107,2.035527,0.935414,-0.267261,-0.816497
3,1.931033,0.721133,0.760886,0.833715,-0.369274,-0.707107,1.137500,-1.069045,-0.267261,1.224745
4,0.019119,0.989323,0.760886,-0.648445,1.477098,1.414214,0.838158,0.935414,-0.267261,-0.816497
5,0.019119,0.631736,0.760886,0.833715,1.477098,-0.707107,1.137500,0.935414,-0.267261,-0.816497
6,1.931033,0.274150,0.760886,0.092635,-0.369274,-0.707107,-0.059868,-1.069045,-0.267261,1.224745
7,1.166268,-0.262230,0.760886,0.000000,-0.369274,-0.707107,-0.359211,-1.069045,3.741657,-0.816497
8,-0.363264,1.168116,-1.314257,-0.648445,-1.292461,-0.707107,0.538816,0.935414,-0.267261,-0.816497
9,0.783885,1.525703,0.760886,0.000000,-1.292461,-0.707107,1.436842,-1.069045,-0.267261,1.224745

## 4.4 Creating New Feature

Pada bagian ini dibuat fitur baru dari fitur yang sudah ada. Contoh fitur baru yang dibuat adalah Produktivitas_Belajar, yaitu hasil perkalian antara Jam_Belajar dan Kehadiran.

In [13]:
df_feature = df_encoded.copy()

df_feature['Produktivitas_Belajar'] = df_feature['Jam_Belajar'] * df_feature['Kehadiran']

df_feature[['Jam_Belajar', 'Kehadiran', 'Produktivitas_Belajar']].head(10)

   Jam_Belajar  Kehadiran  Produktivitas_Belajar
0           23         84                   1932
1           19         64                   1216
2           24         98                   2352
3           29         89                   2581
4           19         92                   1748
5           19         88                   1672
6           29         84                   2436
7           25         78                   1950
8           17         94                   1598
9           23         98                   2254